function lambda = fcn_alphabeta2_lambda(alpha, beta)
lambda = ...
    (168*sin(alpha - pi/9) - 1040*sin(alpha) + ...
    140*sin(alpha - beta))/(147*sin(beta - pi/9) - ...
    910*sin(beta) + 140*sin(alpha - beta));

end